apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-k8s
spec:
  selector:
    matchLabels:
      app: first-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: first-k8s
    spec:
      containers:
      - name: first-k8s
        image: sakar
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4200

